[package]
name = "brainfuck_rust"
version = "1.0.0"
authors = ["Chua Hou <human@chuahou.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
